### ISSUE TITLE
Showing results for latest browser implementations

### ISSUE THREAD

**Issue by yoavweiss** [web-platform-tests/results-collection#106]
First, awesome work on http://wpt.fyi/preload! :)

Currently it exposes the state of web compatibility from a developer's point of view, by showing feature support for shipping browsers, which is great. But for browser implementers and spec authors, it'd be very useful to also get a similar view of latest browser implementations (so Chrome Canary, Safari Tech Preview, MS Edge Creators build and Firefox nightly) with their respective "experimental features" flag on. That would help us realize e.g. if a certain feature implementation is lacking in the version that would eventually ship.

Thanks in advance!

**Comment by yoavweiss** [comment]
Just realized that the results *do* show the latest browsers, other than for Safari.
Would be great to have a split of "present stable" vs. "near future".

**Comment by jgraham** [comment]
So, there are a few different issues wrapped up here:

* Which versions of browsers are tested. I think we are currently using nightly builds of Chrome and Firefox, but just whatever the are the latest builds available on saucelabs for the others. If we have capacity I think it makes sense to run the latest shipping builds + the latest development builds, but in the absence of that capacity latest development builds are more valuable. To get newer versions of Safari and  Edge we would need to find dedicated machines to run them on rather than relying on sauce. For OSX in particular that likely means having an actual box somewhere.
* Which experimental features are enabled. At present, for Firefox, we are using the prefs file from our CI, which does enable some experimental features (it's mostly required to disable things that try to contact external servers during the test run), but often things are enabled per-test-directory rather than once in that prefs file, and those prefs aren't being applied. I don't recall if we are using the experimental features flag for Chrome, but we certainly ought to be. For the others I'm not even sure what exists.

**Comment by foolip** [comment]
Closing this in favor of https://github.com/web-platform-tests/wpt.fyi/issues/60. The first comment links to the issues for the individual browsers, and we expect to have Chrome Dev and Firefox Nightly with their respective "experimental features" flags on within the quarter.
