### ISSUE TITLE
Expose all historical data somewhere public

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#136]
It should be possible to get all the data backing wpt.fyi now and in the past in order to set up a competing instance without coordinating with the maintainers. A manifest of sorts to discover what all the data is should also exist.

@bobholt, what would you propose? I think the only constraint is that it shouldn't be on wpt.fyi itself, in case it's down or slow. Also, when the data grows large enough, wpt.fyi might want to prune some of the data, but the archives can just keep growing. There's some precedent for archive.org + BigQuery within HTTPArchive.

@mdittmer, you might be able to use this for time-based metrics.

**Comment by bobholt** [comment]
@foolip: This can serve as an umbrella issue describing the overall goal for a couple of enhancement issue that @jeffcarp opened a while ago.

- [During result upload, mirror all results to BigQuery](https://github.com/w3c/wptdashboard/issues/43)
- [Give people a way to fetch an index of all TestRuns](https://github.com/w3c/wptdashboard/issues/73)

Right now, there are different Google Compute Engine VMs producing results. Each engine uploads a gzipped JSON summary of results to the Google App Engine instance serving wpt.fyi. There is a test index, but AFAIK, it has to be updated manually (to be fixed in #73).

I think resolving either of the issues above would give us initial public historical data - we can either expose the automatically-updated index of gzipped JSON files on wpt.fyi or provide instructions on how to access the data from BigQuery. Which one we concentrate on should likely come down to what's more useful to whoever wants to access it.

**Comment by foolip** [comment]
That's great, I didn't realize there was already a BigQuery issue.

As for what's useful, I think getting the most recent run as JSON and the full historical dataset in BigQuery would be the way I'm most likely to use it.

**Comment by mattl** [comment]
This came up again when trying to run reports. @jeffcarp pointed us at ``gsutil`` but I think a script to produce this data would be helpful. I'm taking this on.

**Comment by rwaldron** [comment]
To expand a bit more, @mattl and I want to experiment with combining the data after the test run and storing alongside `sha/*-summary.json.gz`

**Comment by mattl** [comment]
And it looks like we can do this by modifying and enhancing ``jenkins.py``

**Comment by foolip** [comment]
Awesome, save all the data! What is the initial output from a run, is that 1 file per test, or 1 combined file? Whatever it is, saving that initial form as well as any potentially useful intermediate forms would be great.

(Storage-wise, maybe file-per-test is better, because they're likely to stay unchanged, and not wasting storage space on exact duplicate files is probably a solved problem in most places one could host the results long term.)

**Comment by mikewest** [comment]
Has there been any movement here? I'm starting to cobble together a dashboard for my team's features, and I'd like to be able to pull the latest run data for a few subdirectories... :)

**Comment by foolip** [comment]
@mikewest, you can still get it all using gsutil. In an [unrelated thing](https://groups.google.com/a/chromium.org/d/msg/ecosystem-infra/yL_DKiDTwiQ/Fc1atwZ3BAAJ) I wrote about what I did: `gsutil -m rsync -r gs://wptd wptd`.

But if you just want the most recent data, you can figure out from https://wpt.fyi/test-runs which directories that is.

**Comment by foolip** [comment]
Also, feature requests that would allow you to use wpt.fyi instead of building your own much appreciated :)

**Comment by foolip** [comment]
Closing in favor of https://github.com/web-platform-tests/wpt.fyi/issues/53
