### ISSUE TITLE
click-cancel.html (using testdriver.js) not working

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/results-collection#220]
See https://wpt.fyi/uievents/order-of-events/mouse-events/click-cancel.html

It should be expected to pass in both Chrome and Edge, and does locally.

**Comment by foolip** [comment]
@mattl, can you help @gsnedders debug what's going on with this one? Since it's a timeout, I suppose you or @gsnedders would have to try adding early `t.done()` in various places to see how far the tests guess. @gsnedders, actually, maybe it's possible to just iterate with Travis CI for that. So assigning to you for now.

**Comment by foolip** [comment]
Ping @gsnedders @mattl. @zcorpan FYI.

**Comment by rwaldron** [comment]
@gsnedders could this be related to https://github.com/w3c/wptdashboard/issues/321

**Comment by foolip** [comment]
It now passes everywhere except Safari, which is because "document.elementsFromPoint unsupported"
