### ISSUE TITLE
Firefox nightly connects to various hosts causing run.py problems.

### ISSUE THREAD

**Issue by mattl** [web-platform-tests/results-collection#443]
I had to add tiles.services.mozilla.com location.services.mozilla.com and normandy.cdn.mozilla.net to 0.0.0.0 in my /etc/hosts.

**Comment by jugglinmike** [comment]
This issue was actually a symptom of a bug in the WPT CLI. [We fixed the problem today](https://github.com/w3c/web-platform-tests/pull/10443), but we'll be maintaining the configuration in order to support reproducing results from older revisions of WPT. [I've documented this in the system configuration](https://github.com/web-platform-tests/results-collection/commit/394359964731766e7c013897c20d2a0e29ce0488), so it's safe to call this issue resolved.
