### ISSUE TITLE
Suggestion: use --no-manifest-update

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#490]
Working on https://github.com/w3c/web-platform-tests/pull/8979 I've noticed that every invocation of `wpt run` tries to update the manifest, which is pointless. If the manifest ever *was* updated as a result, that would be a bug worth not masking too.

(I've claimed elsewhere that the manifest is used as a seed for the hash chunker, but looking at the code that's not actually true. So the risk of messing up the chunking isn't there.)

**Comment by jugglinmike** [comment]
Now that we're distributing the work of collecting results across independent machines, this optimization is no longer appropriate.

(In fact, recent collection attempts have been failing due to the persistence of invalid manifest files--see gh-560. This is another case where shared state has been more of a hindrance than a help.)
