### ISSUE TITLE
Extend identification of result-sets to support multiple versions

### ISSUE THREAD

**Issue by mariestaver** [web-platform-tests/results-collection#512]

**Comment by jugglinmike** [comment]
The issue here is that although we report the browser name and version with each result set, the Golang code differentiates received results by browser name only. This represents a race condition if we were to collect and upload results from two versions of the same browser concurrently. In that case, the version displayed on https://wpt.fyi would be determined by scheduling details (i.e. the results for the most recently-completed browser version would be displayed).

Luke, Robert, and I met today to discuss this. We agreed that in the short term, the runner should upload results for experimental browsers with a distinct name (e.g. `chrome-experimental` and `firefox-experimental`), ensuring consistency with the website's current behavior.

This will be reflected in my initial solution for gh-521 and gh-388. Luke confirmed his intention to make the necessary modifications to the Golang code, so I'll re-assign this issue to him.

**Comment by foolip** [comment]
I *think* this is the same as https://github.com/web-platform-tests/wpt.fyi/issues/60 so I'm closing in favor of that. Possibly there's also work needed in https://github.com/web-platform-tests/wpt.fyi/issues/55 (@Hexcles) to provide all the metadata needed. Please file more issues if something's missing.
