### ISSUE TITLE
Add Firefox Nightly builds

### ISSUE THREAD

**Issue by mariestaver** [web-platform-tests/results-collection#521]

**Comment by jugglinmike** [comment]
We are collecting results for Firefox Nightly as of commit c8952d37985b44ebba85585f5436051cec425f4a . Since this project's focus was recently narrowed to only concern results collection, that commit resolves this issue.  The wpt.fyi website does not currently display this data, but that is no longer a consideration here. See https://github.com/web-platform-tests/wpt.fyi/issues/60 for details on the status of the feature on that website.
