### ISSUE TITLE
Upgrade to Edge 16 and Safari 11.1

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#542]
Edge 16.16299 and Safari 11.1 are available on BrowserStack, and thus presumably also on Sauce.

Upgrading these ought to be one-liners, the real work is in checking if the results are still valid. I would say that spending up to two days on this makes sense, if either browser gives us trouble it might make sense to reconsider options.

**Comment by foolip** [comment]
@mariestaver, this is a task in the "ongoing maintenance" category that I'm not sure how we should deal with planning-wise. It'd be good if there's always some time slack so that (probably) simple things that everyone agrees makes sense can just be done without putting it on roadmap, etc. What process would work for you?

**Comment by mariestaver** [comment]
Thanks for bringing that up, @foolip -- I agree that it'll be easier on everyone if we just set aside time for this (and any other recurring tasks), assuming we can predict when they'll happen.  Do we know how often we expect to need this day-or-two for updates?  

If not, another option is to always build 1-2 days of "slack" into our weekly plans, and then if there are not maintenance tasks like this to take them up, we can use them for either research or kitchen-sink items.  I'll discuss with @zcorpan and @jugglinmike to see what they prefer, too.

**Comment by mariestaver** [comment]
One other question I should ask, @foolip -- Is this (single) update work that you'd like to slot into this week's plan?  If so, we need to discuss which item is losing a day or two of time to make room for it.  (Otherwise, we can just do it next week.)

**Comment by foolip** [comment]
Let's leave this until next week to discuss, not that urgent.

**Comment by jugglinmike** [comment]
For my part, I'm happy to be flexible with our commitments. If a task like this significantly deters us, we can discuss that at the next planning meeting.

That said, a technical detail of this request in particular make on-the-fly prioritization a little tricky. [Last night, we landed a fix](https://github.com/w3c/web-platform-tests/pull/10499) for [a previously-reported bug affecting results from Sauce Labs](https://github.com/web-platform-tests/results-collection/issues/218).  We just missed the 20:00 EST deadline for that day's collection, so we won't be able to vet the changes until the next collection completes some time on the 21st. In order to properly interpret the effect of that change specifically, I'd like to avoid introducing additional variations before Saturday.

So while I agree with @foolip's latest suggestion to wait until next week, I wanted to show that there's also a technical rationale for doing so :)

**Comment by foolip** [comment]
Sounds like we should also make it a priority sooner or later to run more often so that we can iterate faster :)

But maybe not with Sauce...

**Comment by mariestaver** [comment]
Technical AND planning rationale?  It doesn't get better than that!  :D   I'll make sure we circle back to this next week, then.  

There's certainly no harm in changing our priorities anytime something like this comes up, as long as we're keeping track of what other work is affected by the decision.  Thank you again for bringing it to my attention!

**Comment by foolip** [comment]
Sounds like Sauce is still quite slow to upgrade, then. Edge 17 was just released, and it's not on BrowserStack yet, but it would be interesting to see how long the delay is.

**Comment by jugglinmike** [comment]
We've just now upgraded the tested version of Edge again, this time to 17 (see gh-559).

Safari 11.1 continues to be unavailable, but we have an understanding that this project should strive to use the latest versions of the browsers provided by Sauce Labs. In light of that general expectation, I think it's fair to call this issue "resolved" for now.

**Comment by foolip** [comment]
Thanks Mike! Is there some kind of feed where new browsers are announced, or how would we notice when Safari 11.1 becomes available?

**Comment by jugglinmike** [comment]
I looked around for this last night, but between the Sauce Labs website and Twitter account, I couldn't find any announcement.

Maybe @saucelabs can help. Do you folks have a communication channel for announcing new platforms?
