### ISSUE TITLE
Urgent: Incomplete Chrome runs submitted and shown on wpt.fyi

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#553]
The front page of https://wpt.fyi now has a very incomplete Chrome run:
https://wpt.fyi/?sha=722173b215

@Hexcles FYI, as preventing this will become a job for the results receiver, but not yet.

**Comment by foolip** [comment]
Yikes, it's not just one bad run:
https://wpt.fyi/?sha=3e66e833ea

There may be more.

**Comment by jugglinmike** [comment]
Investigating now

**Comment by jugglinmike** [comment]
This was caused by a race condition in scheduling. I'll explain the details,
but the most important parts are:

- I have submitted a patch to correct the problem: gh-554
- We can recover the invalidated datasets without having to re-collect (it will
  just take some scripting)


## The race condition

Here's a flow chart describing the normal case--the vertical describes the
passage of time:

    Build master              Build Workers
    .-------------------.     .--------------------------------------------.
    |                   | <-- | 1. Upload chunk 19 of 20                   |
    |                   |     | 2. Chunks missing--do not schedule upload  |
    |                   |     '--------------------------------------------'
    |                   |     .--------------------------------------------.
    |                   | <-- | 1. Upload chunk 20 of 20                   |
    |                   | <-- | 2. All chunks available--schedule Upload A |
    |                   |     '--------------------------------------------'
    | Upload A          |
    | 1. Upload results |
    |                   |
    |    (uploading)    |
    |                   |
    | 2. Delete chunks  |
    '-------------------'

The pre-condition for this problem is when someone schedules a reduntant build
via the "Retry" button in the Buildbot web UI. If that build completes before
the ongoing "upload" operation, then a second "upload" operation will be
scheduled. This generally isn't a problem because the first operation destroys
the intermediate results.

    Build master              Build Workers
    .-------------------.     .--------------------------------------------.
    |                   | <-- | 1. Upload chunk 19 of 20                   |
    |                   |     | 2. Chunks missing--do not schedule upload  |
    |                   |     '--------------------------------------------'
    |                   |     .--------------------------------------------.
    |                   | <-- | 1. Upload chunk 20 of 20                   |
    |                   | <-- | 2. All chunks available--schedule Upload A |
    |                   |     '--------------------------------------------'
    | Upload A          |     .--------------------------------------------.
    | 1. Upload results |     | Manually-scheduled "retry"                 |
    |                   | <-- | 1. Upload chunk 5 of 20                    |
    |    (uploading)    | <-- | 2. All chunks available--schedule Upload B |
    |                   |     '--------------------------------------------'
    | 2. Delete chunks  |
    |                   |
    | Upload B          |
    | 1. Upload results |
    |    Failure!       |
    |    No chunks      |
    '-------------------'

However, uploading all those files takes about 30 minutes. If a second "retry"
build occurs in this time, then there *will* be results availble when the
superfluous upload operation occurs:

    Build master              Build Workers
    .-------------------.     .--------------------------------------------.
    |                   | <-- | 1. Upload chunk 19 of 20                   |
    |                   |     | 2. Chunks missing--do not schedule upload  |
    |                   |     '--------------------------------------------'
    |                   |     .--------------------------------------------.
    |                   | <-- | 1. Upload chunk 20 of 20                   |
    |                   | <-- | 2. All chunks available--schedule Upload A |
    |                   |     '--------------------------------------------'
    | Upload A          |     .--------------------------------------------.
    | 1. Upload results |     | Manually-scheduled "retry"                 |
    |                   | <-- | 1. Upload chunk 5 of 20                    |
    |    (uploading)    | <-- | 2. All chunks available--schedule Upload B |
    |                   |     '--------------------------------------------'
    | 2. Delete chunks  |
    |                   |     .-------------------------------------------.
    | (busy)            |     | Manually-scheduled "retry"                |
    |                   | <-- | 1. Upload chunk 11 of 20                  |
    |                   | <-- | 2. Chunks missing--do not schedule upload |
    |                   |     '-------------------------------------------'
    | Upload B          |
    | 1. Upload results |
    |                   |
    |    (uploading)    |
    |                   |
    | 2. Delete chunks  |
    '-------------------'

If this series of events seems unlikely, I agree. Speaking personally, I only
request "retries" for failed builds--there's no reason to retry a successful
build.

By reviewing the build log (included below), we can see that a number of builds
were needlessly retried on last Thursday. Although we limit access to this
functionality based on GitHub organization membership, Buildbot does not appear
to offer audit logs with this information.

## Correcting the problem

In any case, the fix is clear: verify that the expected number of files are
present before uploading. I've deployed a patch to implement this guard.

## Recovering prior results

we use an "rsync" style command to upload results. That means only
the "summary" file is incorrect--all of the individual results files are still
available. We can download them and re-create the summary manually.

<details>
  <summary>Listing of all builds for revision 7f8492376ee91c220a59fdc6553471ed7cb37cf8</summary>

Platform identifier          | Chunk | Link | Started at | Finished at
-----------------------------|----|-------------------------------------------------|--------------------------|-------------------------
firefox-experimental-linux   |  1 | [25045](http://builds.wpt.fyi/#/builders/3/builds/25045) | 2018-05-03T20:00:22.000Z | 2018-05-03T20:37:24.000Z
firefox-experimental-linux   |  2 | [25046](http://builds.wpt.fyi/#/builders/3/builds/25046) | 2018-05-03T20:00:22.000Z | 2018-05-03T20:42:52.000Z
firefox-experimental-linux   |  3 | [25047](http://builds.wpt.fyi/#/builders/3/builds/25047) | 2018-05-03T20:00:22.000Z | 2018-05-03T20:11:56.000Z
firefox-experimental-linux   |  4 | [25048](http://builds.wpt.fyi/#/builders/3/builds/25048) | 2018-05-03T20:00:23.000Z | 2018-05-03T20:21:51.000Z
firefox-experimental-linux   |  5 | [25049](http://builds.wpt.fyi/#/builders/3/builds/25049) | 2018-05-03T20:00:23.000Z | 2018-05-03T20:47:49.000Z
firefox-experimental-linux   |  6 | [25050](http://builds.wpt.fyi/#/builders/3/builds/25050) | 2018-05-03T20:00:23.000Z | 2018-05-03T20:21:48.000Z
firefox-experimental-linux   |  7 | [25051](http://builds.wpt.fyi/#/builders/3/builds/25051) | 2018-05-03T20:00:24.000Z | 2018-05-03T20:38:41.000Z
firefox-experimental-linux   |  8 | [25052](http://builds.wpt.fyi/#/builders/3/builds/25052) | 2018-05-03T20:00:24.000Z | 2018-05-03T20:23:39.000Z
firefox-experimental-linux   |  9 | [25053](http://builds.wpt.fyi/#/builders/3/builds/25053) | 2018-05-03T20:00:25.000Z | 2018-05-03T20:42:00.000Z
firefox-experimental-linux   | 10 | [25054](http://builds.wpt.fyi/#/builders/3/builds/25054) | 2018-05-03T20:00:25.000Z | 2018-05-03T20:49:10.000Z
firefox-experimental-linux   | 11 | [25055](http://builds.wpt.fyi/#/builders/3/builds/25055) | 2018-05-03T20:00:26.000Z | 2018-05-03T21:15:04.000Z
firefox-experimental-linux   | 12 | [25056](http://builds.wpt.fyi/#/builders/3/builds/25056) | 2018-05-03T20:00:27.000Z | 2018-05-03T20:53:44.000Z
firefox-experimental-linux   | 13 | [25057](http://builds.wpt.fyi/#/builders/3/builds/25057) | 2018-05-03T20:00:28.000Z | 2018-05-03T20:18:18.000Z
firefox-experimental-linux   | 14 | [25058](http://builds.wpt.fyi/#/builders/3/builds/25058) | 2018-05-03T20:00:29.000Z | 2018-05-03T20:50:43.000Z
firefox-experimental-linux   | 15 | [25059](http://builds.wpt.fyi/#/builders/3/builds/25059) | 2018-05-03T20:00:30.000Z | 2018-05-03T20:28:46.000Z
firefox-experimental-linux   | 16 | [25060](http://builds.wpt.fyi/#/builders/3/builds/25060) | 2018-05-03T20:00:31.000Z | 2018-05-03T20:33:12.000Z
firefox-experimental-linux   | 17 | [25061](http://builds.wpt.fyi/#/builders/3/builds/25061) | 2018-05-03T20:00:32.000Z | 2018-05-03T20:42:42.000Z
firefox-experimental-linux   | 18 | [25062](http://builds.wpt.fyi/#/builders/3/builds/25062) | 2018-05-03T20:00:34.000Z | 2018-05-03T20:19:42.000Z
firefox-experimental-linux   | 19 | [25063](http://builds.wpt.fyi/#/builders/3/builds/25063) | 2018-05-03T20:00:36.000Z | 2018-05-03T20:36:04.000Z
firefox-experimental-linux   | 20 | [25064](http://builds.wpt.fyi/#/builders/3/builds/25064) | 2018-05-03T20:00:37.000Z | 2018-05-03T20:13:24.000Z
chrome-experimental-linux    |  1 | [25065](http://builds.wpt.fyi/#/builders/3/builds/25065) | 2018-05-03T20:00:42.000Z | 2018-05-03T20:22:11.000Z
chrome-experimental-linux    |  2 | [25066](http://builds.wpt.fyi/#/builders/3/builds/25066) | 2018-05-03T20:00:43.000Z | 2018-05-03T20:28:45.000Z
chrome-experimental-linux    |  3 | [25067](http://builds.wpt.fyi/#/builders/3/builds/25067) | 2018-05-03T20:00:44.000Z | 2018-05-03T20:14:32.000Z
chrome-experimental-linux    |  4 | [25068](http://builds.wpt.fyi/#/builders/3/builds/25068) | 2018-05-03T20:00:46.000Z | 2018-05-03T20:16:06.000Z
chrome-experimental-linux    |  5 | [25069](http://builds.wpt.fyi/#/builders/3/builds/25069) | 2018-05-03T20:00:48.000Z | 2018-05-03T20:22:47.000Z
chrome-experimental-linux    |  6 | [25070](http://builds.wpt.fyi/#/builders/3/builds/25070) | 2018-05-03T20:00:49.000Z | 2018-05-03T20:13:22.000Z
chrome-experimental-linux    |  7 | [25071](http://builds.wpt.fyi/#/builders/3/builds/25071) | 2018-05-03T20:00:51.000Z | 2018-05-03T21:31:50.000Z
chrome-experimental-linux    |  8 | [25072](http://builds.wpt.fyi/#/builders/3/builds/25072) | 2018-05-03T20:00:52.000Z | 2018-05-03T20:25:53.000Z
chrome-experimental-linux    |  9 | [25073](http://builds.wpt.fyi/#/builders/3/builds/25073) | 2018-05-03T20:00:54.000Z | 2018-05-03T21:56:49.000Z
chrome-experimental-linux    | 10 | [25074](http://builds.wpt.fyi/#/builders/3/builds/25074) | 2018-05-03T20:00:57.000Z | 2018-05-03T23:06:32.000Z
chrome-experimental-linux    | 11 | [25075](http://builds.wpt.fyi/#/builders/3/builds/25075) | 2018-05-03T20:11:57.000Z | 2018-05-03T21:16:14.000Z
chrome-experimental-linux    | 12 | [25076](http://builds.wpt.fyi/#/builders/3/builds/25076) | 2018-05-03T20:13:22.000Z | 2018-05-03T20:36:08.000Z
chrome-experimental-linux    | 13 | [25077](http://builds.wpt.fyi/#/builders/3/builds/25077) | 2018-05-03T20:13:24.000Z | 2018-05-03T20:29:01.000Z
chrome-experimental-linux    | 14 | [25078](http://builds.wpt.fyi/#/builders/3/builds/25078) | 2018-05-03T20:14:32.000Z | 2018-05-03T20:50:00.000Z
chrome-experimental-linux    | 15 | [25079](http://builds.wpt.fyi/#/builders/3/builds/25079) | 2018-05-03T20:16:06.000Z | 2018-05-03T20:45:09.000Z
chrome-experimental-linux    | 16 | [25080](http://builds.wpt.fyi/#/builders/3/builds/25080) | 2018-05-03T20:18:18.000Z | 2018-05-03T20:34:46.000Z
chrome-experimental-linux    | 17 | [25081](http://builds.wpt.fyi/#/builders/3/builds/25081) | 2018-05-03T20:19:42.000Z | 2018-05-03T20:43:41.000Z
chrome-experimental-linux    | 18 | [25082](http://builds.wpt.fyi/#/builders/3/builds/25082) | 2018-05-03T20:21:48.000Z | 2018-05-03T20:31:29.000Z
chrome-experimental-linux    | 19 | [25083](http://builds.wpt.fyi/#/builders/3/builds/25083) | 2018-05-03T20:21:51.000Z | 2018-05-03T20:54:09.000Z
chrome-experimental-linux    | 20 | [25084](http://builds.wpt.fyi/#/builders/3/builds/25084) | 2018-05-03T20:22:12.000Z | 2018-05-03T20:28:19.000Z
chrome-stable-linux          |  1 | [25085](http://builds.wpt.fyi/#/builders/3/builds/25085) | 2018-05-03T20:22:47.000Z | 2018-05-03T20:42:05.000Z
chrome-stable-linux          |  2 | [25086](http://builds.wpt.fyi/#/builders/3/builds/25086) | 2018-05-03T20:23:39.000Z | 2018-05-03T20:52:41.000Z
chrome-stable-linux          |  3 | [25087](http://builds.wpt.fyi/#/builders/3/builds/25087) | 2018-05-03T20:25:54.000Z | 2018-05-03T20:39:07.000Z
chrome-stable-linux          |  4 | [25088](http://builds.wpt.fyi/#/builders/3/builds/25088) | 2018-05-03T20:28:19.000Z | 2018-05-03T20:43:01.000Z
chrome-stable-linux          |  5 | [25089](http://builds.wpt.fyi/#/builders/3/builds/25089) | 2018-05-03T20:28:46.000Z | 2018-05-03T22:00:28.000Z
chrome-stable-linux          |  6 | [25090](http://builds.wpt.fyi/#/builders/3/builds/25090) | 2018-05-03T20:28:46.000Z | 2018-05-03T20:41:22.000Z
chrome-stable-linux          |  7 | [25091](http://builds.wpt.fyi/#/builders/3/builds/25091) | 2018-05-03T20:29:01.000Z | 2018-05-03T21:02:16.000Z
chrome-stable-linux          |  8 | [25092](http://builds.wpt.fyi/#/builders/3/builds/25092) | 2018-05-03T20:31:29.000Z | 2018-05-03T20:45:32.000Z
chrome-stable-linux          |  9 | [25093](http://builds.wpt.fyi/#/builders/3/builds/25093) | 2018-05-03T20:33:13.000Z | 2018-05-03T21:01:34.000Z
chrome-stable-linux          | 10 | [25094](http://builds.wpt.fyi/#/builders/3/builds/25094) | 2018-05-03T20:34:47.000Z | 2018-05-03T21:18:14.000Z
chrome-stable-linux          | 11 | [25095](http://builds.wpt.fyi/#/builders/3/builds/25095) | 2018-05-03T20:36:04.000Z | 2018-05-03T21:41:14.000Z
chrome-stable-linux          | 12 | [25096](http://builds.wpt.fyi/#/builders/3/builds/25096) | 2018-05-03T20:36:08.000Z | 2018-05-03T21:02:04.000Z
chrome-stable-linux          | 13 | [25097](http://builds.wpt.fyi/#/builders/3/builds/25097) | 2018-05-03T20:37:24.000Z | 2018-05-03T20:53:06.000Z
chrome-stable-linux          | 14 | [25098](http://builds.wpt.fyi/#/builders/3/builds/25098) | 2018-05-03T20:38:42.000Z | 2018-05-03T21:12:33.000Z
chrome-stable-linux          | 15 | [25099](http://builds.wpt.fyi/#/builders/3/builds/25099) | 2018-05-03T20:39:07.000Z | 2018-05-03T20:56:15.000Z
chrome-stable-linux          | 16 | [25100](http://builds.wpt.fyi/#/builders/3/builds/25100) | 2018-05-03T20:41:22.000Z | 2018-05-03T20:59:30.000Z
chrome-stable-linux          | 17 | [25101](http://builds.wpt.fyi/#/builders/3/builds/25101) | 2018-05-03T20:42:00.000Z | 2018-05-03T21:08:41.000Z
chrome-stable-linux          | 18 | [25102](http://builds.wpt.fyi/#/builders/3/builds/25102) | 2018-05-03T20:42:05.000Z | 2018-05-03T20:51:53.000Z
chrome-stable-linux          | 19 | [25103](http://builds.wpt.fyi/#/builders/3/builds/25103) | 2018-05-03T20:42:42.000Z | 2018-05-03T21:15:51.000Z
firefox-stable-linux         |  7 | [25104](http://builds.wpt.fyi/#/builders/3/builds/25104) | 2018-05-03T20:42:52.000Z | 2018-05-03T21:19:48.000Z
firefox-stable-linux         |  8 | [25105](http://builds.wpt.fyi/#/builders/3/builds/25105) | 2018-05-03T20:43:01.000Z | 2018-05-03T21:02:20.000Z
chrome-stable-linux          | 20 | [25106](http://builds.wpt.fyi/#/builders/3/builds/25106) | 2018-05-03T20:43:42.000Z | 2018-05-03T20:49:33.000Z
firefox-stable-linux         |  1 | [25107](http://builds.wpt.fyi/#/builders/3/builds/25107) | 2018-05-03T20:45:09.000Z | 2018-05-03T21:22:16.000Z
firefox-stable-linux         |  2 | [25108](http://builds.wpt.fyi/#/builders/3/builds/25108) | 2018-05-03T20:45:32.000Z | 2018-05-03T21:22:33.000Z
firefox-stable-linux         |  3 | [25109](http://builds.wpt.fyi/#/builders/3/builds/25109) | 2018-05-03T20:47:49.000Z | 2018-05-03T21:05:39.000Z
firefox-stable-linux         |  4 | [25110](http://builds.wpt.fyi/#/builders/3/builds/25110) | 2018-05-03T20:49:10.000Z | 2018-05-03T21:09:43.000Z
firefox-stable-linux         |  5 | [25111](http://builds.wpt.fyi/#/builders/3/builds/25111) | 2018-05-03T20:49:33.000Z | 2018-05-03T21:31:31.000Z
firefox-stable-linux         |  6 | [25112](http://builds.wpt.fyi/#/builders/3/builds/25112) | 2018-05-03T20:50:00.000Z | 2018-05-03T21:13:05.000Z
firefox-stable-linux         |  9 | [25113](http://builds.wpt.fyi/#/builders/3/builds/25113) | 2018-05-03T20:50:43.000Z | 2018-05-03T21:32:08.000Z
firefox-stable-linux         | 10 | [25114](http://builds.wpt.fyi/#/builders/3/builds/25114) | 2018-05-03T20:51:53.000Z | 2018-05-03T21:50:17.000Z
firefox-stable-linux         | 11 | [25115](http://builds.wpt.fyi/#/builders/3/builds/25115) | 2018-05-03T20:52:41.000Z | 2018-05-03T22:06:49.000Z
firefox-stable-linux         | 12 | [25116](http://builds.wpt.fyi/#/builders/3/builds/25116) | 2018-05-03T20:53:06.000Z | 2018-05-03T21:39:58.000Z
firefox-stable-linux         | 13 | [25117](http://builds.wpt.fyi/#/builders/3/builds/25117) | 2018-05-03T20:53:44.000Z | 2018-05-03T21:11:44.000Z
firefox-stable-linux         | 14 | [25118](http://builds.wpt.fyi/#/builders/3/builds/25118) | 2018-05-03T20:54:09.000Z | 2018-05-03T21:43:52.000Z
firefox-stable-linux         | 15 | [25119](http://builds.wpt.fyi/#/builders/3/builds/25119) | 2018-05-03T20:56:15.000Z | 2018-05-03T21:23:59.000Z
firefox-stable-linux         | 16 | [25120](http://builds.wpt.fyi/#/builders/3/builds/25120) | 2018-05-03T20:59:30.000Z | 2018-05-03T21:30:10.000Z
firefox-stable-linux         | 17 | [25121](http://builds.wpt.fyi/#/builders/3/builds/25121) | 2018-05-03T21:01:34.000Z | 2018-05-03T21:41:33.000Z
firefox-stable-linux         | 18 | [25122](http://builds.wpt.fyi/#/builders/3/builds/25122) | 2018-05-03T21:02:04.000Z | 2018-05-03T21:26:18.000Z
firefox-stable-linux         | 19 | [25123](http://builds.wpt.fyi/#/builders/3/builds/25123) | 2018-05-03T21:02:16.000Z | 2018-05-03T21:36:34.000Z
firefox-stable-linux         | 20 | [25124](http://builds.wpt.fyi/#/builders/3/builds/25124) | 2018-05-03T21:02:21.000Z | 2018-05-03T22:04:34.000Z
chrome-experimental-linux    |  7 | [25125](http://builds.wpt.fyi/#/builders/3/builds/25125) | 2018-05-03T21:15:51.000Z | 2018-05-03T21:48:41.000Z
chrome-experimental-linux    |  9 | [25126](http://builds.wpt.fyi/#/builders/3/builds/25126) | 2018-05-03T21:15:51.000Z | 2018-05-03T21:44:29.000Z
chrome-experimental-linux    | 10 | [25127](http://builds.wpt.fyi/#/builders/3/builds/25127) | 2018-05-03T21:15:51.000Z | 2018-05-03T21:58:40.000Z
chrome-experimental-linux    | 11 | [25128](http://builds.wpt.fyi/#/builders/3/builds/25128) | 2018-05-03T21:15:51.000Z | 2018-05-03T22:21:05.000Z
chrome-stable-linux          |  5 | [25129](http://builds.wpt.fyi/#/builders/3/builds/25129) | 2018-05-03T21:15:51.000Z | 2018-05-03T21:38:36.000Z
chrome-stable-linux          | 10 | [25130](http://builds.wpt.fyi/#/builders/3/builds/25130) | 2018-05-03T21:15:52.000Z | 2018-05-03T21:58:15.000Z
chrome-stable-linux          | 11 | [25131](http://builds.wpt.fyi/#/builders/3/builds/25131) | 2018-05-03T21:15:52.000Z | 2018-05-03T22:23:05.000Z
firefox-stable-linux         |  1 | [25132](http://builds.wpt.fyi/#/builders/3/builds/25132) | 2018-05-03T21:15:52.000Z | 2018-05-03T21:52:43.000Z
firefox-stable-linux         |  7 | [25133](http://builds.wpt.fyi/#/builders/3/builds/25133) | 2018-05-03T21:16:14.000Z | 2018-05-03T21:50:44.000Z
firefox-stable-linux         |  2 | [25134](http://builds.wpt.fyi/#/builders/3/builds/25134) | 2018-05-03T21:18:14.000Z | 2018-05-03T21:55:45.000Z
firefox-stable-linux         |  5 | [25135](http://builds.wpt.fyi/#/builders/3/builds/25135) | 2018-05-03T21:19:48.000Z | 2018-05-03T22:04:06.000Z
firefox-stable-linux         |  9 | [25136](http://builds.wpt.fyi/#/builders/3/builds/25136) | 2018-05-03T21:22:16.000Z | 2018-05-03T22:00:55.000Z
firefox-stable-linux         | 10 | [25137](http://builds.wpt.fyi/#/builders/3/builds/25137) | 2018-05-03T21:22:33.000Z | 2018-05-03T22:21:51.000Z
firefox-stable-linux         | 11 | [25138](http://builds.wpt.fyi/#/builders/3/builds/25138) | 2018-05-03T21:24:00.000Z | 2018-05-03T22:36:14.000Z
firefox-stable-linux         | 12 | [25139](http://builds.wpt.fyi/#/builders/3/builds/25139) | 2018-05-03T21:26:18.000Z | 2018-05-03T22:13:22.000Z
firefox-stable-linux         | 17 | [25140](http://builds.wpt.fyi/#/builders/3/builds/25140) | 2018-05-03T21:30:10.000Z | 2018-05-03T22:11:12.000Z
firefox-stable-linux         | 19 | [25141](http://builds.wpt.fyi/#/builders/3/builds/25141) | 2018-05-03T21:31:31.000Z | 2018-05-03T22:04:44.000Z
firefox-stable-linux         | 20 | [25142](http://builds.wpt.fyi/#/builders/3/builds/25142) | 2018-05-03T21:31:50.000Z | 2018-05-03T21:43:01.000Z
firefox-stable-linux         | 14 | [25143](http://builds.wpt.fyi/#/builders/3/builds/25143) | 2018-05-03T21:32:08.000Z | 2018-05-03T22:24:25.000Z

</details>

**Comment by foolip** [comment]
Excellent investigation as usual, @jugglinmike! Looks like all of the problematic builds were from the same day? If that's the case, and this problem hasn't occurred repeatedly over time, then perhaps just deleting the bad runs would be OK. @lukebjerring, WDYT?

@mdittmer @Hexcles, note also how this means that when converting existing runs to submit them to the new results receiver, it's possible there are cases when the summary file disagrees with the other files in storage. Catching this case and looking into it might reveal something interesting.

**Comment by lukebjerring** [comment]
Currently that's the caes, but after changing the endpoint, we'll only be submitting the full report, so the summary becomes irrelevant.
I'd stick with a behaviour of marking them as `bad`, and not deleting things. @mdittmer expressed desire for some process around this when it occurs (notifying somehow).

Perhaps we could add a 'notes' field to the runs? Or similar - ideas welcome.
I'd also like to progress the `label` concept to include `bad`, and even eventually have an administrative UI of some sort.

**Comment by jugglinmike** [comment]
Thanks, @foolip. The issue you reported was caused by two independent problems:

1. Someone triggered multiple redundant builds
2. I did not design the system to account for this

Without audit logs, there's not much we can do to address `#1`. The system ought to be resilient to such mistakes, regardless of who is making them. So even though we can't call `#1` "solved", the patch available at gh-554 makes it a non-issue.

> I'd stick with a behaviour of marking them as `bad`, and not deleting things. @mdittmer expressed desire for some process around this when it occurs (notifying somehow).
>
> Perhaps we could add a 'notes' field to the runs? Or similar - ideas welcome.

These are good ideas for @hexcles' new system, but for the current system, we should try to limit change as much as possible. Renaming technically works, but our current procedure could be improved. [I recently pitched an idea about this](https://github.com/web-platform-tests/wpt.fyi/issues/110#issuecomment-386004065), but it probably got lost in the flood of my ramblings here and elsewhere on GitHub. To make discussion easier, I've formalized that suggestion into a patch to this project's maintenance instructions: gh-555.
