### ISSUE TITLE
Upload WPT report to staging.wpt.fyi

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/results-collection#565]
In preparation of migrating to the full-report based system on wpt.fyi, let's double-upload, sending the full report to staging.wpt.fyi for integration testing.

**Comment by lukebjerring** [comment]
See https://github.com/web-platform-tests/wpt.fyi/issues/192 for wpt.fyi side of things.

**Comment by Hexcles** [comment]
@jugglinmike I have a question for you:

In the [upload script](https://github.com/web-platform-tests/results-collection/blob/master/src/scripts/upload-wpt-results.py), do you already have the merged full report JSOn available at some point?

**Comment by jugglinmike** [comment]
> In the [upload script](https://github.com/web-platform-tests/results-collection/blob/master/src/scripts/upload-wpt-results.py), do you already have the merged full report JSON available at some point?

Not currently. The "WPT report"-formatted results are stored on disk across many files, and they are individually parsed and stored in the legacy wpt.fyi format.

I avoided merging those files in the "WPT report" format because this would unnecessarily increase the memory footprint of the process. It's necessary now, though, so you can expect a patch to change this.

Here's what I'll need:

- the URL to which the data should be sent
- the expected HTTP method
- the expected HTTP headers
- the expected request body

**Comment by Hexcles** [comment]
A code snippet is probably more helpful:

```python
# For Chrome & Firefox, report.json should have all the metadata.
requests.post(
    'https://wptdashboard-staging.appspot.com/api/results/upload',
    auth=('buildbot', 'secret_token'),
    files={'result_file': open('full_report.json.gz', 'rb')},
# For Sauce-based browsers you'd also need the following:
    data={'browser_name': ..., 'browser_version': ..., 'os_name': ..., 'os_version': ...}
)
```

Ideally I'd like to include the browser & OS info in the report even for Sauce. I'm looking into that.

**Comment by jugglinmike** [comment]
Got it. Can you send me the token via e-mail? I will include it in the encrypted configuration file that's tracked within this repo

**Comment by Hexcles** [comment]
@jugglinmike can you give me your pubkey?

**Comment by jugglinmike** [comment]
Sure: https://keybase.io/jugglinmike
