### ISSUE TITLE
No Safari results since Aug 23

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#597]
https://staging.wpt.fyi/test-runs?label=stable

The latest Safari results are currently https://staging.wpt.fyi/results/?sha=d2fa1bdc90, from Aug 23. (The wpt commit itself is from Aug 22.)

**Comment by jugglinmike** [comment]
Thanks for the report! Unfortunately, as of yesterday, we are not collecting
results from either Sauce Labs-mediated browser. I've filed a separate issue,
gh-598, since the fact that it effects *both* browsers likely means it is
unrelated to the Safari-specific problem. I'm going to hold off on diagnosing
this problem because gh-598 appears to be systemic.

**Comment by foolip** [comment]
@jugglinmike, should this be closed now?
