### ISSUE TITLE
No Edge runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/results-collection#628]
Right now https://foolip.github.io/ecosystem-infra-rotation/ is red in this manner:
![image](https://user-images.githubusercontent.com/498917/48410122-fee14e80-e73d-11e8-90f2-335ddf584a1d.png)

This is because there is no Edge run in the past 24 hours, the last one was on Friday. This is long enough that it's probably not because of https://github.com/web-platform-tests/results-collection/issues/623.

**Comment by jugglinmike** [comment]
It looks like the overall build time for Edge has exceeded 24 hours. This would be problematic enough if Buildbot used a fair scheduling algorithm since results would slowly become less and less timely. Unfortunately, Buildbot appears to assign jobs to workers randomly. Workers are currently collecting results for the 8th, 9th, and 10th. No work for the 11th, 12th, or today has begun.

I'm going to revert 27c22db74aefb3e1ae93d34a76c7c9502ce48b64 in order to reduce the time-to-results. [Recall that the change was an experimental optimization.](https://github.com/web-platform-tests/results-collection/issues/563#issuecomment-431505583) We haven't determined if it actually improved correctness. Reverting the change may reduce result accuracy, but not beyond the point we've been reporting for the past year.

Prior to that change, Edge required 15 hours to complete. The wall time will likely be even smaller now that all Sauce Labs jobs are dedicated solely to Edge, but it's difficult to predict the extent of the improvement.

Still, I'm pessimistic that we'll be able to recover from this state in a timely fashion. I'm going to cancel the previous 3 days of builds with the hope that we'll be able to complete the three earlier collections and be ready to start tomorrow's collection immediately.

**Comment by foolip** [comment]
We've had Edge runs since this issue was last active.
